name: myapp
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  path: ^1.8.3
  flutter_mobx: ^2.0.6+5
  flutter_rating_bar: ^4.0.1
  booking_calendar: ^1.1.10

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
